services:
  email-accessor-service:
    build:
      context: ./ # במבנה שלך זה מציין שה-Dockerfile נמצא בתיקייה הזו
    container_name: email-accessor-service
    ports:
      - "3013:3013" # המפה את הפורט המקומי
    environment:
      - DAPR_HTTP_PORT=3513
      - DAPR_GRPC_PORT=50113
    networks:
      - network-dapr

  email-accessor-service-dapr:
    image: "daprio/daprd:1.14.4"
    container_name: email-accessor-service-dapr
    command: [
      "./daprd",
      "-app-port", "3013",
      "-app-id", "email-accessor-service",
      "-app-protocol", "http",
      "-dapr-http-port", "3513",
      "--resources-path", "/dapr/components",
      "-config", "/dapr/config.yaml",
      "--log-level", "debug"
    ]
    volumes:
      - "./dapr/components:/dapr/components"
      - "./dapr/config.yaml:/dapr/config.yaml"
    depends_on:
      - email-accessor-service
    networks:
      - network-dapr

networks:
  network-dapr:
    driver: bridge
